# Generated by Django 5.1.1 on 2024-09-23 12:21

import books.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
            bases=(books.models.TrackedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
            bases=(books.models.TrackedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
            bases=(books.models.TrackedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn_no', models.TextField(max_length=13, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('language', models.TextField(max_length=50)),
                ('publication_date', models.DateField()),
                ('blob_path', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.genre')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.publisher')),
            ],
            bases=(books.models.TrackedMixin, models.Model),
        ),
    ]
