# Generated by Django 5.1.1 on 2024-11-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='blob_path',
            field=models.FileField(upload_to=''),
        ),
    ]
