# Generated by Django 4.2.16 on 2024-11-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_page_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(default=0),
        ),
    ]
