# Generated by Django 4.2.16 on 2024-11-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='object_details',
            field=models.TextField(null=True),
        ),
    ]
